name: murza_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.2
  get_it: ^8.0.3
  mask_text_input_formatter: ^2.9.0
  url_launcher: ^6.2.5
  dio: ^5.8.0+1
  equatable: ^2.0.7
  cached_network_image: ^3.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
